name: event_db_tester
description: Provides a testing utility for event_db. Mainly through genericModelTest
version: 0.2.0
repository: https://github.com/VHCBlade/event_db_tester

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  event_bloc_tester: ^0.1.6
  event_db: ^0.2.0

  test: ^1.21.0
  tuple: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  very_good_analysis: ^5.0.0
